tlc_trip:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DWH_HOST') }}"
      port: "{{ env_var('DWH_PORT') | int }}"
      user: "{{ env_var('DWH_USER') }}"
      password: "{{ env_var('DWH_PASSWORD') }}"
      dbname: "{{ env_var('DWH_DBNAME') }}"
      schema: "{{ env_var('DWH_SCHEMA') }}"
      threads: 2