version: 2

models:
  - name: fact_yellow_taxi_trips
    description: "Data trips of yellow taxi from TLC trip"

  - name: dim_date
    description: "Date dimension table"

  - name: dim_time
    description: "Time dimension table"

  - name: stg_payment_type
    description: "Type of payment"

  - name: stg_location
    description: "Location"

  - name: stg_vendor
    description: "Vendor"

  - name: stg_rate_code
    description: "Rate code"

